volumes:
  dev-db-volume: {}

services:
  dev-pg12:
    container_name: blps
    image: postgres:17
    environment:
      POSTGRES_DB: blpsdb
      POSTGRES_USER: blps
      POSTGRES_PASSWORD: blps
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    volumes:
      - dev-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blps -d blpsdb"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge