volumes:
  dev-db-volume: {}
services:
  dev-pg12:
    container_name: blps
    hostname: lala4
    image: bitnami/postgresql:17.2.0
    environment:
      POSTGRESQL_DATABASE: blpsdb
      POSTGRESQL_USERNAME: blps
      POSTGRESQL_PASSWORD: blps
    volumes:
      - dev-db-volume:/bitnami/postgresql
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blpsdb"]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge
